version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - redis
    environment: 
      REDIS_URL: redis:6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
