version: '3.9'
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://app:8080
  worker1:
    image: locustio/locust
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
  worker2:
    image: locustio/locust
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master