version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 5120M
volumes:
  mongodata: