version: '3.9'
services:
  app:
    build: 
      context: ../python/
    image: lecz0/simple-crud-python:latest
    ports:
      - "8080:8080"
    environment: 
      MONGO_URI: mongodb://root:testpassword@mongo:27017
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
